apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: samirprakash/auth
      context: auth
    - image: samirprakash/client
      context: client
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
      artifacts:
        - image: samirprakash/auth
          context: auth
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              # Sync all the typescript files that are in the src folder
              # with the container src folder
              - src: 'src/**/*.ts'
                dest: .
        - image: samirprakash/client
          context: client
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              # Sync all the typescript files that are in the src folder
              # with the container src folder
              - src: '**/*.js'
                dest: .
