import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ticketing Client Q!</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1>Ticketing Landing Page</h1>
      </div>
    </div>
  );
}
